#version: "3.9"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dbrest
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: always

    volumes:
      - pg_data:/var/lib/postgresql/data
      #- ../data-drf:/var/lib/postgresql/data


volumes:
  pg_data:
    

