# buildspec file for aws codebuild django drf application
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running migrations"
      - python manage.py migrate
  build:
    commands:
      - echo "Collecting static files"
      - python manage.py collectstatic --noinput
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - '**/*'
  base-directory: flightServices

   

